<?php

namespace GoodToKnow\Controllers;

class process_a_commodity_sale_save
{
    function page()
    {
        /**
         * Save the commodity and commodity_sold records generated by the previous
         * route. Also, retrieve these records back from the database and present
         * them to the user as confirmation that all went well.
         *
         * Make sure all session variables are destroyed at the end of the script.
         */


        global $g;


        kick_out_loggedoutusers();


        get_db();


        /**
         * The commodity and commodity_sold records are (now) in a state which is appropriate
         * to be saved to the database although at one point in time in the previous route,
         * these records were modified to be human-readable for the confirmation view.
         */

        //$g->saved_arr02 has commodity
        //$g->saved_arr03 has commodity_sold

    }
}