<?php

namespace GoodToKnow\Controllers;

class process_a_commodity_sale_save
{
    function page()
    {
        /**
         * Save the commodity and commodity_sold records generated by the previous
         * route. Also, retrieve these records back from the database and present
         * them to the user as confirmation that all went well.
         *
         * Make sure all session variables are destroyed at the end of the script.
         */


        global $g;


        kick_out_loggedoutusers();


        get_db();


        /**
         * Make sure the commodity and commodity_sold records are in a state which
         * is appropriate to be saved to the database before saving them. As you may
         * recall, these records were modified to be presentable in the confirmation
         * view. The code for accomplishing this should be in the previous route.
         */

        //$g->saved_arr02 commodity
        //$g->saved_arr03 commodity_sold

        /**
         * Debug Code
         */
        echo "\n<p>Begin debug</p>\n";
        echo "<p>commodity \$g->saved_arr02: </p>\n<pre>";
        var_dump($g->saved_arr02);
        echo "</pre>\n";
        echo "<p>commodity_sold \$g->saved_arr03: </p>\n<pre>";
        var_dump($g->saved_arr03);
        echo "</pre>\n";
        die("<p>End debug</p>\n");
    }
}